name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Dependências do Projeto
      run: npm install

    - name: Ajustar permissões para ESLint
      run: chmod +x ./node_modules/.bin/eslint 
      
    - name: Executar Lint
      run: npx eslint .

    - name: Executar Testes Unitários
      run: npm test

    - name: Executar Testes de Sistema Cypress
      run: npx cypress run
