name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Dependências do Projeto
      run: npm install

    - name: Cache Cypress Binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-cypress-  

    - name: Ajustar permissões para Cypress
      run: chmod +x ./node_modules/.bin/cypress
          
    - name: instalar Cypress
      run: npx cypress install

    - name: Ajustar permissões para ESLint
      run: chmod +x ./node_modules/.bin/eslint 
      
    - name: Executar Lint
      run: npx eslint . || echo "ESLint"
    
    - name: Ajustar permissões para o Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Executar Testes Unitários
      run: npm test || echo "Jest"

    - name: Executar Testes de Sistema Cypress
      run: npx cypress run || echo "Cypress"
